apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signature-forgery-ingress
  namespace: signature-forgery
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: signature-forgery.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signature-forgery-service
                port:
                  number: 8501
