apiVersion: v1
kind: Service
metadata:
  name: signature-forgery-service
  labels:
    app: signature-forgery-app
spec:
  type: NodePort
  selector:
    app: signature-forgery-app
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
